config/routes.rb
Rails.application.routes.draw do

  get 'notifications/index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root "top#index"

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :topics do
    resources :comments
  end

  resources :users, only: [:index, :show]

  resources :relationships, only: [:create, :destroy]

  resources :conversations do
    resources :messages
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :topic
  has_many :notifications, dependent: :destroy
  default_scope {order(:id)}

  validates :content, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only:[:edit, :update, :destroy]
  before_action :set_topic, only:[:edit, :update]

  def create
    @comment = current_user.comments.build(comment_params)
    @topic = @comment.topic
    unless @topic.user_id == @comment.user_id
      @notification = @comment.notifications.build(user_id: @topic.user.id, notification_type: "comment")
    end

    respond_to do |format|
      if @comment.save
        flash.now[:notice] = "コメントを投稿しました。"
        format.js { render :index }
        execute_kuma_comment_reply(@topic)

        Pusher.trigger("user_#{@comment.topic.user_id}_channel", 'notification_created', {
          unread_counts: Notification.where(user_id: @comment.topic.user.id, read: false).count
        })
      else
        format.js { render :index }
      end
    end
  end

  def edit
  end

  def update
    if @comment.update(comment_params)
      redirect_to topic_path(@topic), notice: "コメントを更新しました。"
    else
      render "edit"
    end
  end

  def destroy
    @comment.destroy
    flash.now[:notice] = "コメントを削除しました。"
    respond_to do |format|
      format.js {render :index}
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:topic_id, :content)
    end

    def set_comment
      @comment = Comment.find(params[:id])
    end
    def set_topic
      @topic = Comment.find(params[:id]).topic
    end

    def execute_kuma_comment_reply(topic)
      writer = User.find(topic.user_id)
      if writer.provider == "kuma_provider"
        writer.delay(run_at: 10.seconds.from_now).create_kuma_comment(topic)
      end
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for([topic,comment], remote: true) do |f| %>
  <%= f.hidden_field :topic_id %>
  <div class="field">
    <%= f.text_field :content, placeholder: "コメントを入力", class: "form-control"  %>
  </div>
  <%= f.submit "コメントする", class: "btn btn-primary margin-top5px hidden-xs" %>
  <%= f.submit "コメントする", class: "btn btn-primary margin-top5px btn-block visible-xs" %>
<% end %>

app/views/comments/_index.html.erb
<ul>
  <% comments.each do |comment| %>
    <% unless comment.id.nil? %>
      <li>
        <p class="left"><%= profile_img(comment.user,size: :small) %>
          &nbsp;&nbsp;<b><%= comment.user.name %></b>（<%= comment.created_at.in_time_zone('Tokyo').strftime("%Y年%m月%d日 %H時%M分%S秒") %>）
          <% if current_user.id == comment.user.id %>
            <%= link_to '', edit_topic_comment_path(topic, comment), class: "fa fa-pencil-square-o fa-lg" %>
            <%= link_to '', topic_comment_path(topic, comment), class: "fa fa-trash-o fa-lg", method: :delete, remote: true, data: { confirm: "本当に削除していいですか？" } %>
          <% end %>
        </p>
        <p>&nbsp;&nbsp;<%= comment.content %></p>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/comments/edit.html.erb
<h2 class="page-header">コメントを編集する</h2>

<% if @comment.errors.any? %>
  <div class="form-group alert alert-danger">
    <div id="error_explanation">
      <h2><%= @comment.errors.count %>件のエラーがあります。</h2>
      <ul>
        <% @comment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

<%= form_for([@topic, @comment]) do |f| %>
  <%= f.hidden_field :topic_id %>
  <div class="field">
    <%= f.text_field :content, placeholder: "コメントを入力", class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit "コメントする", class: "btn btn-primary margin-top5px hidden-xs" %>
    <%= f.submit "コメントする", class: "btn btn-primary margin-top5px btn-block visible-xs" %>
  </div>
<% end %>

<p class="h4 margin-top15px">
  <%= link_to 'トピックに戻る', topic_path(@topic) %>
</p>

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'comments/index', { comments: @comment.topic.comments, topic: @comment.topic }) %>")
$(':text').val('')
$("p#notice").html("<%= j(flash[:notice]) %>")