config/routes.rb
Rails.application.routes.draw do

  get 'notifications/index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root "top#index"

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :topics do
    resources :comments
  end

  resources :users, only: [:index, :show]

  resources :relationships, only: [:create, :destroy]

  resources :conversations do
    resources :messages
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  default_scope {order(id: :desc)}

  mount_uploader :image, ImageUploader

  validates :title, :content, presence: true
  validates :content, format: {with: /[(くま)(クマ)(熊)(bear)(ぱんだ)(パンダ)(panda)]/, message: "には「くま」「クマ」「熊」などの語句を含めてください (ᵔᴥᵔ)"}
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  def index
    user_ids = current_user.followed_users.ids
    user_ids << current_user.id
    @topics = Topic.where(user_id: user_ids).includes(:comments)
  end

  def new
    if params[:back]
      @topic = Topic.new(topic_params)
    else
      @topic = Topic.new
    end
  end

  def create
    @topic = Topic.new(topic_params)
    @topic.user_id = current_user.id
    if @topic.save
      execute_kuma_comment_write(@topic)
      redirect_to topics_path, notice: "トピックを作成しました"
      NoticeMailer.sendmail_topic(@topic).deliver
    else
      render "new"
    end
  end

  def show
    @comment = @topic.comments.build
    @comments = @topic.comments
    Notification.find(params[:notification_id]).update(read: true) if params[:notification_id]
    @notifications_count = Notification.where(user_id: current_user.id).where(read: false).count
  end

  def edit
  end

  def update
    if @topic.update(topic_params)
      redirect_to topics_path, notice: "トピックを編集しました"
    else
      render "edit"
    end
  end

  def destroy
    @topic.destroy
    redirect_to topics_path, notice: "トピックを削除しました"
  end

  private
  def topic_params
    params.require(:topic).permit(:title, :content, :image)
  end

  def set_topic
    @topic = Topic.find(params[:id])
  end

  def execute_kuma_comment_write(topic)
    kuma_followers = current_user.followers.find_all{|user| user.provider == "kuma_provider"}
    return if kuma_followers.blank?
    random = Random.new
    kuma_followers.each do |kuma|
      kuma.delay(run_at: random.rand(60).seconds.from_now).create_kuma_comment(topic)
    end
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
  def comment_outline(topic)
    if topic.comments.present?
      "（" + topic.comments.count.to_s + "件のコメントがあります。）"
    else
      "（コメントはありません。）"
    end
  end
end

app/views/topics/_form.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible">
    <button class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <p><%= notice %><%= alert %></p>
  </div>
<% end %>

<p>くまの話題を投稿してね！ʕ•ᴥ•ʔ</p><br>
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div class="form-group alert alert-danger">
      <div id="error_explanation">
        <h2><%= @topic.errors.count %>件のエラーがあります。</h2>
        <ul>
          <% @topic.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <br>
  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, class: "form-control", rows: 8 %>
  </div>
  <br>
  <div class="form-group">
    <%= image_tag @topic.image.url if @topic.image? %><br>
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  <br>
  <%= f.submit "投稿する", class: "btn btn-primary hidden-xs"%>
  <%= f.submit "投稿する", class: "btn btn-primary btn-block visible-xs"%>
<% end %>
<br>
<p class="h4 margin-top15px">
  <%= link_to "トピック一覧画面に戻る", topics_path %>
</p>

app/views/topics/edit.html.erb
<h2 class="page-header">トピックを編集する</h2>
<%= render "form" %>

app/views/topics/index.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible">
    <button class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <p><%= notice %><%= alert %></p>
  </div>
<% end %>

<% if @topics.blank?%>
  <p class="margin-top100px"><%= image_tag("kuma_icon", class: "img-responsive center-block") %></p>
  <p class="h4 text-center text-muted">ユーザをフォローするとトピックが表示されるよ！</p>
  <p class="h4 text-center text-muted">ユーザのフォローは<%= link_to "こちら", users_path %>から</p>
  <p class="h4 text-center text-muted">トピックの投稿は<%= link_to "こちら", new_topic_path %>から</p>
<% else %>
  <% @topics.each do |topic| %>
    <div class="panel panel-default margin-top40px">
      <div class="panel-heading">
        <h2 class="panel-title">
            <%= profile_img(topic.user, size: :small) %>&nbsp;&nbsp;投稿者：<%= topic.user.name %>
            <br class="visible-xs"><br class="visible-xs">
            （<%= topic.created_at.in_time_zone('Tokyo').strftime("%Y年%m月%d日 %H時%M分%S秒") %>）
        </h2>
      </div>
      <div class="panel-body">
        <p>
          <strong class="h3"><%= topic.title %></strong><hr>
          <% if topic.img_url.present? %>
            <img src="<%= topic.img_url %>" alt="<%= topic.title %>" class="img-responsive center-block"><br>
          <% elsif topic.image.present? %>
            <%= image_tag(topic.image, alt: topic.title, class: "img-responsive center-block") %><br>
          <% end %>
          <%= simple_format(h(topic.content)) %>
        </p>
      </div>
      <div class="panel-footer">
        <% if current_user == topic.user %>
          <div class="hidden-xs clearfix">
            <%= link_to "コメント機能", topic_path(topic.id), class: "btn btn-info pull-left" %>
            &nbsp;<%= comment_outline(topic) %>
            <%= link_to "投稿を削除する", topic_path(topic.id), method: :delete, data: { confirm: "本当に削除していいですか？" }, class: "btn btn-danger pull-right" %>
            <span class="pull-right">&nbsp;</span>
            <%= link_to "投稿を編集する", edit_topic_path(topic.id), class: "btn btn-success pull-right" %>
          </div>
          <div class="visible-xs">
            <%= link_to "コメント機能", topic_path(topic.id), class: "btn btn-info btn-block" %>
            <div class="text-center"><%= comment_outline(topic) %></div>
            <%= link_to "投稿を編集する", edit_topic_path(topic.id), class: "btn btn-success btn-block" %>
            <%= link_to "投稿を削除する", topic_path(topic.id), method: :delete, data: { confirm: "本当に削除していいですか？" }, class: "btn  btn-danger btn-block" %>
          </div>
        <% else %>
          <div class="hidden-xs">
            <%= link_to "コメント機能", topic_path(topic.id), class: "btn btn-info" %>
            <%= comment_outline(topic) %>
          </div>
          <div class="visible-xs">
            <%= link_to "コメント機能", topic_path(topic.id), class: "btn btn-info btn-block" %>
            <div class="text-center"><%= comment_outline(topic) %></div>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>


<section>
  <div id="page-top-btn" class="page-top-btn">
      <p><a class="move-page-top" id="move-page-top">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;▲</a></p>
  </div>
</section>

app/views/topics/new.html.erb
<h2 class="page-header">トピックを投稿する</h2>
<%= render "form" %>

app/views/topics/show.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible">
    <button class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <p><%= notice %><%= alert %></p>
  </div>
<% end %>

<div class="panel panel-default margin-top40px">
  <div class="panel-heading">
    <h2 class="panel-title">
        <%= profile_img(@topic.user, size: :small) %>&nbsp;&nbsp;投稿者：<%= @topic.user.name %>
        <br class="visible-xs"><br class="visible-xs">
        （<%= @topic.created_at.in_time_zone('Tokyo').strftime("%Y年%m月%d日 %H時%M分%S秒") %>）
    </h2>
  </div>
  <div class="panel-body">
    <p>
      <strong class="h3"><%= @topic.title %></strong><hr>
      <% if @topic.img_url.present? %>
        <img src="<%= @topic.img_url %>" alt="<%= @topic.title %>" class="img-responsive center-block"><br>
      <% elsif @topic.image.present? %>
        <%= image_tag(@topic.image, alt: @topic.title, class: "img-responsive center-block") %><br>
      <% end %>
      <%= simple_format(h(@topic.content)) %>
    </p>
  </div>
  <div class="panel-footer">
    <p class="h3">コメント一覧</p>
    <div id="comments_area">
      <%= render partial: 'comments/index', locals: { comments: @comments, topic: @topic } %>
    </div>
    <%= render partial: 'comments/form', locals: { comment: @comment, topic: @topic } %>
    <p class="h4 margin-top15px">
      <% if current_user.id == @topic.user_id %>
        <%= link_to 'トピック編集', edit_topic_path(@topic) %>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;
      <% end %>
      <%= link_to '一覧に戻る', topics_path %>
    </p>
  </div>
</div>

<section>
  <div id="page-top-btn" class="page-top-btn">
      <p><a class="move-page-top" id="move-page-top">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;▲</a></p>
  </div>
</section>